
USE PAGE_VIEW_10_20_2020_DB;
SELECT ARTICLE_NAME, SUM(ARTICLE_VIEWS) AS TOTAL_VIEWS_DESKTOP
FROM PAGE_VIEW_GENERAL_DATA
WHERE LANGUAGE='en'
GROUP BY ARTICLE_NAME
ORDER BY TOTAL_VIEWS_DESKTOP DESC
LIMIT 10;

###############################################################################

USE CLICK_STREAM_311_411_DB;
CREATE TABLE CLICK_STREAM_ARTICLE_VIEWED_BOTH
(REFERRER STRING, ARTICLE_VIEWS_BOTH INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE CLICK_STREAM_ARTICLE_VIEWED_BOTH
SELECT REFERRER, SUM(CURRENT_ARTICLE_VIEWS)
FROM CLICK_STREAM_GENERAL_DATA
GROUP BY REFERRER;
CREATE TABLE CLICK_STREAM_ARTICLE_VIEWED_INTERNALLY 
(REFERRER STRING, ARTICLE_VIEWS_INTERNALLY INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE CLICK_STREAM_ARTICLE_VIEWED_INTERNALLY  
SELECT REFERRER, SUM(CURRENT_ARTICLE_VIEWS)
FROM CLICK_STREAM_GENERAL_DATA
WHERE LINK_TYPE='link'
GROUP BY REFERRER;
CREATE TABLE CLICK_STREAM_ARTICLE_VIEWED_FRACTIONALLY 
(REFERRER STRING, ARTICLE_VIEWS_BOTH INT, ARTICLE_VIEWS_INTERNALLY INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE CLICK_STREAM_ARTICLE_VIEWED_FRACTIONALLY 
SELECT B.REFERRER, B.ARTICLE_VIEWS_BOTH, I.ARTICLE_VIEWS_INTERNALLY 
FROM CLICK_STREAM_ARTICLE_VIEWED_BOTH B 
INNER JOIN CLICK_STREAM_ARTICLE_VIEWED_INTERNALLY I
ON (B.REFERRER=I.REFERRER);
SELECT REFERRER, ARTICLE_VIEWS_BOTH, ARTICLE_VIEWS_INTERNALLY, 
ROUND(((ARTICLE_VIEWS_INTERNALLY/ARTICLE_VIEWS_BOTH)*100),3) AS INTERNAL_FRACTIONAL_VIEW
FROM CLICK_STREAM_ARTICLE_VIEWED_FRACTIONALLY
WHERE ARTICLE_VIEWS_INTERNALLY > 1000000
GROUP BY REFERRER, ARTICLE_VIEWS_BOTH, ARTICLE_VIEWS_INTERNALLY
ORDER BY INTERNAL_FRACTIONAL_VIEW DESC
LIMIT 20;

##########################################################################

USE CLICK_STREAM_311_411_DB;
CREATE TABLE CLICK_STREAM_HC_ARTICLE_VIEWED_BOTH
(CURRENT_ARTICLE STRING, REFERRER STRING, ARTICLE_VIEWS_BOTH INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO CLICK_STREAM_HC_ARTICLE_VIEWED_BOTH
SELECT CURRENT_ARTICLE, REFERRER, SUM(CURRENT_ARTICLE_VIEWS)
FROM CLICK_STREAM_GENERAL_DATA 
WHERE REFERRER LIKE 'Hotel_California%'
GROUP BY CURRENT_ARTICLE, REFERRER;
CREATE TABLE CLICK_STREAM_HC_ARTICLE_VIEWED_INTERNALLY 
(CURRENT_ARTICLE STRING, REFERRER STRING, ARTICLE_VIEWS_INTERNALLY INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO CLICK_STREAM_HC_ARTICLE_VIEWED_INTERNALLY 
SELECT CURRENT_ARTICLE, REFERRER, SUM(CURRENT_ARTICLE_VIEWS)
FROM CLICK_STREAM_GENERAL_DATA 
WHERE REFERRER LIKE 'Hotel_California%' AND LINK_TYPE='link'
GROUP BY CURRENT_ARTICLE, REFERRER;
CREATE TABLE CLICK_STREAM_HC_ARTICLE_VIEWED_FRACTIONALLY 
(CURRENT_ARTICLE STRING, REFERRER STRING, ARTICLE_VIEWS_BOTH INT, ARTICLE_VIEWS_INTERNALLY INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE CLICK_STREAM_HC_ARTICLE_VIEWED_FRACTIONALLY 
SELECT  B.CURRENT_ARTICLE, B.REFERRER, B.ARTICLE_VIEWS_BOTH, I.ARTICLE_VIEWS_INTERNALLY 
FROM CLICK_STREAM_HC_ARTICLE_VIEWED_BOTH B 
INNER JOIN CLICK_STREAM_HC_ARTICLE_VIEWED_INTERNALLY I
ON (B.REFERRER=I.REFERRER) AND (B.CURRENT_ARTICLE=I.CURRENT_ARTICLE);
SELECT CURRENT_ARTICLE, REFERRER, ARTICLE_VIEWS_BOTH, ARTICLE_VIEWS_INTERNALLY, 
ROUND(((ARTICLE_VIEWS_INTERNALLY/ARTICLE_VIEWS_BOTH)*100),3) AS INTERNAL_FRACTIONAL_VIEW
FROM CLICK_STREAM_HC_ARTICLE_VIEWED_FRACTIONALLY
GROUP BY CURRENT_ARTICLE, REFERRER, ARTICLE_VIEWS_BOTH, ARTICLE_VIEWS_INTERNALLY
ORDER BY ARTICLE_VIEWS_INTERNALLY DESC
LIMIT 20;

################################################################################

USE COUNTRY_BASED_VIEWS_DB;
CREATE TABLE US_DATA_SIMPLIFIED 
(ARTICLE_NAME STRING, ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE US_DATA_SIMPLIFIED
SELECT ARTICLE_NAME, SUM(ARTICLE_VIEWS) AS ARTICLE_VIEWS
FROM US_PAGE_VIEWS_GENERAL_DATA 
WHERE DOMAIN='en'
GROUP BY ARTICLE_NAME;
CREATE TABLE ARTICLES_MOST_VIEWED_IN_UNITED_STATES
(ARTICLE_NAME STRING, ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE ARTICLES_MOST_VIEWED_IN_UNITED_STATES
SELECT ARTICLE_NAME, ARTICLE_VIEWS
FROM US_DATA_SIMPLIFIED 
WHERE ARTICLE_NAME != 'Main_Page' 
AND 
ARTICLE_NAME != '-' 
AND 
ARTICLE_NAME != 'Special:Search'
ORDER BY ARTICLE_VIEWS DESC
LIMIT 5;
CREATE TABLE UK_DATA_SIMPLIFIED 
(ARTICLE_NAME STRING, ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE UK_DATA_SIMPLIFIED
SELECT ARTICLE_NAME, SUM(ARTICLE_VIEWS) AS ARTICLE_VIEWS
FROM UK_PAGE_VIEWS_GENERAL_DATA 
WHERE DOMAIN='en'
GROUP BY ARTICLE_NAME;
CREATE TABLE ARTICLES_MOST_VIEWED_IN_UNITED_KINGDOM
(ARTICLE_NAME STRING, ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE ARTICLES_MOST_VIEWED_IN_UNITED_KINGDOM
SELECT ARTICLE_NAME, ARTICLE_VIEWS
FROM UK_DATA_SIMPLIFIED 
WHERE ARTICLE_NAME != 'Main_Page'
AND 
ARTICLE_NAME != '-' 
AND 
ARTICLE_NAME != 'Special:Search'
ORDER BY ARTICLE_VIEWS DESC
LIMIT 5;
CREATE TABLE AUS_DATA_SIMPLIFIED 
(ARTICLE_NAME STRING, ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE AUS_DATA_SIMPLIFIED
SELECT ARTICLE_NAME, SUM(ARTICLE_VIEWS) AS ARTICLE_VIEWS
FROM AUS_PAGE_VIEWS_GENERAL_DATA 
WHERE DOMAIN='en'
GROUP BY ARTICLE_NAME;
CREATE TABLE ARTICLES_MOST_VIEWED_IN_AUSTRALIA
(ARTICLE_NAME STRING, ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE ARTICLES_MOST_VIEWED_IN_AUSTRALIA
SELECT ARTICLE_NAME, ARTICLE_VIEWS
FROM AUS_DATA_SIMPLIFIED 
WHERE ARTICLE_NAME != 'Main_Page'
AND 
ARTICLE_NAME != '-' 
AND 
ARTICLE_NAME != 'Special:Search'
ORDER BY ARTICLE_VIEWS DESC
LIMIT 5;
SELECT * FROM ARTICLES_MOST_VIEWED_IN_UNITED_STATES;
SELECT * FROM ARTICLES_MOST_VIEWED_IN_UNITED_KINGDOM;
SELECT * FROM ARTICLES_MOST_VIEWED_IN_AUSTRALIA;

###############################################################

USE REVISION_USER_HISTORY_PAGE_DB;
CREATE TABLE PAGE_RESTORE_TIMESTAMP
(PAGE_TITLE STRING,
PAGE_FIXED_UNIX_TIMESTAMP BIGINT,
PAGE_FIXED_TIMESTAMP STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO PAGE_RESTORE_TIMESTAMP
SELECT PAGE_TITLE, (SUM(VANDALISM_UNIX_TIMESTAMP) + SUM(PAGE_FIXED_TIMELAPSE)), 
FROM_UNIXTIME((SUM(VANDALISM_UNIX_TIMESTAMP) + SUM(PAGE_FIXED_TIMELAPSE)))
FROM REVISION_USER_HISTORY_PAGE_SIMPLIFIED_GENERAL_DATA
GROUP BY PAGE_TITLE;
CREATE TABLE JANUARY_2020_VANDALISMS
(PAGE_TITLE STRING,
VANDALISM_TIMESTAMP STRING,
PAGE_FIXED_TIMESTAMP STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO JANUARY_2020_VANDALISMS
SELECT SGD.PAGE_TITLE, SGD.VANDALISM_TIMESTAMP, PRT.PAGE_FIXED_TIMESTAMP 
FROM REVISION_USER_HISTORY_PAGE_SIMPLIFIED_GENERAL_DATA AS SGD 
INNER JOIN PAGE_RESTORE_TIMESTAMP AS PRT
ON SGD.PAGE_TITLE = PRT.PAGE_TITLE
WHERE SGD.VANDALISM_UNIX_TIMESTAMP > 1577836800 
AND 
PRT.PAGE_FIXED_UNIX_TIMESTAMP BETWEEN 1577836800 AND 1580515200;
CREATE TABLE CLICK_STREAM_VIEWS
(CURRENT_ARTICLE STRING, CURRENT_ARTICLE_VIEWS INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO TABLE CLICK_STREAM_VIEWS
SELECT CURRENT_ARTICLE, SUM(CURRENT_ARTICLE_VIEWS)
FROM CLICK_STREAM_GENERAL_DATA
GROUP BY CURRENT_ARTICLE;
CREATE TABLE ARTICLES_VANDALIZED
(PAGE_TITLE STRING,VANDALISM_TIMESTAMP STRING,
PAGE_FIXED_TIMESTAMP STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO ARTICLES_VANDALIZED
SELECT JV.PAGE_TITLE, JV.VANDALISM_TIMESTAMP,
JV.PAGE_FIXED_TIMESTAMP
FROM JANUARY_2020_VANDALISMS AS JV 
INNER JOIN 
CLICK_STREAM_VIEWS AS CSV
ON JV.PAGE_TITLE = CSV.CURRENT_ARTICLE
ORDER BY CSV.CURRENT_ARTICLE_VIEWS DESC
LIMIT 6;
SELECT *
FROM ARTICLES_VANDALIZED;  
CREATE TABLE VIEWS_BEFORE_FIXED
(ARTICLE STRING, VIEWS_BEFORE_VANDALISM_REVERSED INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO VIEWS_BEFORE_FIXED
SELECT PVGD.ARTICLE_NAME, SUM(PVGD.ARTICLE_VIEWS)
FROM PAGE_VIEW_GENERAL_DATA_1_03 AS PVGD 
INNER JOIN 
ARTICLES_VANDALIZED AS AC
ON PVGD.ARTICLE_NAME = AC.PAGE_TITLE
WHERE AC.PAGE_TITLE='Esmail_Ghaani'
GROUP BY PVGD.ARTICLE_NAME;
INSERT INTO VIEWS_BEFORE_FIXED
SELECT PVGD.ARTICLE_NAME, SUM(PVGD.ARTICLE_VIEWS)
FROM PAGE_VIEW_GENERAL_DATA_1_05 AS PVGD 
INNER JOIN 
ARTICLES_VANDALIZED AS AC
ON PVGD.ARTICLE_NAME = AC.PAGE_TITLE
WHERE AC.PAGE_TITLE='Dr._Romantic_2'
GROUP BY PVGD.ARTICLE_NAME;
INSERT INTO VIEWS_BEFORE_FIXED
SELECT PVGD.ARTICLE_NAME, SUM(PVGD.ARTICLE_VIEWS)
FROM PAGE_VIEW_GENERAL_DATA_1_08_09_10 AS PVGD 
INNER JOIN 
ARTICLES_VANDALIZED AS AC
ON PVGD.ARTICLE_NAME = AC.PAGE_TITLE
WHERE AC.PAGE_TITLE='Circles_(Mac_Miller_album)'
GROUP BY PVGD.ARTICLE_NAME;
INSERT INTO VIEWS_BEFORE_FIXED
SELECT PVGD.ARTICLE_NAME, SUM(PVGD.ARTICLE_VIEWS)
FROM PAGE_VIEW_GENERAL_DATA_1_06 AS PVGD 
INNER JOIN 
ARTICLES_VANDALIZED AS AC
ON PVGD.ARTICLE_NAME = AC.PAGE_TITLE
WHERE AC.PAGE_TITLE='Reynhard_Sinaga'
GROUP BY PVGD.ARTICLE_NAME;
SELECT *
FROM VIEWS_BEFORE_FIXED;
SELECT AVG(VIEWS_BEFORE_VANDALISM_REVERSED) AS AVERAGE_VIEWS_BEFORE_OFFENDING_EDIT_IS_REVERSED
FROM VIEWS_BEFORE_FIXED;

###################################################################

USE CORONAVIRUS_SEARCH_BY_COUNTRY_DB;
CREATE TABLE CORONAVIRUS_SEARCH_BY_DOMAIN
(DOMAIN STRING, AMOUNT_SEARCHED INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t';
INSERT INTO CORONAVIRUS_SEARCH_BY_DOMAIN
SELECT DOMAIN, SUM(ARTICLE_VIEWS) AS AMOUNT_SEARCHED
FROM PAGE_VIEWS_GENERAL_DATA_405
WHERE ARTICLE_NAME LIKE '%coronavirus%'
GROUP BY DOMAIN
ORDER BY AMOUNT_SEARCHED DESC
LIMIT 10;
SELECT *
FROM CORONAVIRUS_SEARCH_BY_DOMAIN;